export const OTP_EXPIRY_TIME = 5 * 60 * 1000;
export const OTP_TIME = 1440;

//Exception constants

//AUTH
export const USER_UNAUTHORIZED_ERROR_CODE = 7;
export const INVALID_OTP_AUTHENTIFICATION_ERROR_CODE = 5;
export const INVALID_REFRESH_AUTHENTIFICATION_ERROR_CODE = 51;
export const INVALID_ACCESS_AUTHENTIFICATION_ERROR_CODE = 52;

//ACCOUNT
export const ACCOUNT_EXISTS_CLIENT_EXCEPTION_CODE = 41;
export const ACCOUNT_NOT_FOUND_EXCEPTION_CODE = 4;

//OTP
export const OTP_INTERNAL_SERVER_ERROR_CODE = 6;
//SERVER
export const SERVER_ERROR = 574;
