export const OTP_EXPIRY_TIME = 5 * 60 * 1000;
export const OTP_TIME = 1440;
export const VACUUM_FREE_LIMIT = 3;

//Exception constants

//AUTH
export const USER_UNAUTHORIZED_ERROR_CODE = 7;
export const INVALID_OTP_AUTHENTIFICATION_ERROR_CODE = 5;
export const INVALID_REFRESH_AUTHENTIFICATION_ERROR_CODE = 51;
export const INVALID_ACCESS_AUTHENTIFICATION_ERROR_CODE = 52;

//ACCOUNT
export const ACCOUNT_EXISTS_CLIENT_EXCEPTION_CODE = 41;
export const ACCOUNT_NOT_FOUND_EXCEPTION_CODE = 4;
export const PHONE_NUMBERS_DO_NOT_MATCH = 45;
export const META_NOT_FOUND_EXCEPTION_CODE = 9;
export const META_EXISTS_CLIENT_EXCEPTION_CODE = 42;
export const CARD_NOT_MATCH_EXCEPTION_CODE = 43;
//OTP
export const OTP_INTERNAL_SERVER_ERROR_CODE = 6;

//ORDER
export const ORDER_ERROR_CODES = {
  PROCESSING_ERROR: 995, // Use existing code
  ORDER_NOT_FOUND: 1000,
  INVALID_ORDER_STATE: 1001,
  PAYMENT_CANCELED: 1002,
  PAYMENT_TIMEOUT: 1003,
  ORDER_CREATION_FAILED: 1004,
  INSUFFICIENT_REWARD_POINTS: 1005,
  REWARD_POINTS_WITHDRAWAL_FAILED: 1006,
  CARD_FOR_ORDER_NOT_FOUND: 1007,
  INSUFFICIENT_FREE_VACUUM: 1008,
  CASHBACK_ACCRUAL_FAILED: 1009,
};

//POS
export const BAY_IS_BUSY_ERROR_CODE = 81;
export const CARWASH_UNAVALIBLE_ERROR_CODE = 89;
export const CARWASH_START_FAILED = 1100;

//PROMOCODE
export const PROMO_CODE_NOT_FOUND_ERROR_CODE = 84;
export const INVALID_PROMO_CODE_ERROR_CODE = 88;
//SERVER
export const SERVER_ERROR = 574;
  
//PAYMENT
export const PAYMENT_ERROR_CODES = {
  PROCESSING_ERROR: 1199, // Use existing code
  PAYMENT_REGISTRATION_FAILED: 1200,
  INVALID_WEBHOOK_SIGNATURE: 1201,
  MISSING_ORDER_ID: 1202,
  MISSING_PAYMENT_ID: 1203,
  REFUND_FAILED: 1204,
};
