export const OTP_EXPIRY_TIME = 5 * 60 * 1000;
export const OTP_TIME = 1440;

//Exception constants

//AUTH
export const USER_UNAUTHORIZED_ERROR_CODE = 7;
export const INVALID_OTP_AUTHENTIFICATION_ERROR_CODE = 5;
export const INVALID_REFRESH_AUTHENTIFICATION_ERROR_CODE = 51;
export const INVALID_ACCESS_AUTHENTIFICATION_ERROR_CODE = 52;

//ACCOUNT
export const ACCOUNT_EXISTS_CLIENT_EXCEPTION_CODE = 41;
export const ACCOUNT_NOT_FOUND_EXCEPTION_CODE = 4;
export const META_NOT_FOUND_EXCEPTION_CODE = 9;
export const META_EXISTS_CLIENT_EXCEPTION_CODE = 42;
export const CARD_NOT_MATCH_EXCEPTION_CODE = 43;
//OTP
export const OTP_INTERNAL_SERVER_ERROR_CODE = 6;
//ORDER
export const ORDER_PROCESSING_ERROR_CODE = 8;

export const BAY_IS_BUSY_ERROR_CODE = 81;
export const CARWASH_UNAVALIBLE_ERROR_CODE = 89;

//PROMOCODE
export const PROMO_CODE_NOT_FOUND_ERROR_CODE = 84;
export const INVALID_PROMO_CODE_ERROR_CODE = 88;
//SERVER
export const SERVER_ERROR = 574;

//PAYMENT
export const PAYMENT_PROCESSING_ERROR_CODE = 91;
